import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import { Link } from 'react-router-dom';
import StarField from '../components/bits/StarField.jsx';

const fadeUp = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0 } };

const metalStyle = {
  background: 'linear-gradient(180deg, #E6C76A 0%, #D4AF37 40%, #C9A227 70%, #E6C76A 100%)',
  WebkitBackgroundClip: 'text',
  WebkitTextFillColor: 'transparent',
  backgroundClip: 'text',
};

const categories = [
  {
    title: '🔮 The Product and How It Works',
    items: [
      {
        q: 'What exactly is the Crystal Code?',
        a: "It's a premium crystal sphere with a unique engraved QR, presented in a luxury black box. When you scan the QR, you enter your birth date, time, and place and access your Abundance Code portal — your personal block analysis based on your birth chart.",
      },
      {
        q: 'Do I need to know astrology to use it?',
        a: 'No. The analysis is written in clear, direct language. No jargon. No prior knowledge needed.',
      },
      {
        q: 'Is it really personalized or is it generic content?',
        a: "It's genuinely personalized. Your exact birth date, time, and place generate a unique combination. No two analyses are the same.",
      },
      {
        q: "What if I don't know my birth time?",
        a: 'You can enter an approximate time or leave it blank. The analysis will still be personalized, though some specific aspects may be less precise.',
      },
    ],
  },
  {
    title: '🚚 Shipping and Delivery',
    items: [
      {
        q: 'How long does my Crystal Code take to arrive?',
        a: 'Processing takes 1-3 business days. Shipping varies by location, generally 5-15 business days for international orders.',
      },
      {
        q: 'Do you ship worldwide?',
        a: 'Yes. We ship internationally. Costs and delivery times vary by destination country.',
      },
      {
        q: 'Can I access the portal before receiving the sphere?',
        a: 'Yes. As soon as you confirm your purchase you receive access to a portal preview. The sphere activates your full analysis upon arrival.',
      },
      {
        q: 'How do I track my order?',
        a: "Once shipped, you'll receive an email with a tracking number to follow your order in real time.",
      },
    ],
  },
  {
    title: '📱 The Portal and Technology',
    items: [
      {
        q: 'How does the portal work?',
        a: "It's a private web page accessible from any device. When you scan your sphere's QR and enter your birth details, your personalized analysis is generated with your Abundance Code, energy symbol, activation ritual, and daily guide.",
      },
      {
        q: 'Does the portal expire?',
        a: 'No. Access is for life. Once activated, your portal will always be available.',
      },
      {
        q: 'Do I need to download an app?',
        a: 'No. The portal works directly from your phone or computer browser. No downloads. No installations.',
      },
      {
        q: 'Does the QR only work once?',
        a: 'No. You can scan your crystal as many times as you want to access your portal from any device.',
      },
    ],
  },
  {
    title: '💳 Payments and Guarantee',
    items: [
      {
        q: 'What payment methods do you accept?',
        a: 'We accept credit and debit cards, PayPal, and other methods available by country. All payments are processed securely.',
      },
      {
        q: 'How does the 7-day guarantee work?',
        a: "If within 7 days of receiving the product you feel it's not what you expected, contact our support and we'll refund you completely. No questions. No complications.",
      },
      {
        q: 'Is it safe to pay on the site?',
        a: 'Yes. We use SSL encryption and certified payment processors. Your financial information is never stored on our servers.',
      },
    ],
  },
  {
    title: '✨ Astrology and AI',
    items: [
      {
        q: 'How is my analysis generated?',
        a: 'Your analysis is generated by artificial intelligence trained in astrological interpretation. From your exact birth date, time, and place, your birth chart is constructed and the patterns influencing different areas of your life are identified.',
      },
      {
        q: 'Do I need to believe in astrology for it to work?',
        a: "No. You don't need to believe in anything. You just need to see if what it describes resonates with your real life. Many people who arrive skeptical are surprised by the accuracy of the analysis.",
      },
      {
        q: "Is it the same as a horoscope?",
        a: "No. A horoscope is generic for millions of people. Your analysis is specific to you, based on your exact birth chart — the unique combination of your birth date, time, and place.",
      },
    ],
  },
  {
    title: '💎 The Bracelet and Bundle',
    items: [
      {
        q: 'What is the energy bracelet?',
        a: "It's a physical complement designed to integrate your transformation process into daily life. It works as a constant reminder of your energetic alignment — to carry your intention with you beyond the crystal.",
      },
      {
        q: 'Can I buy just the bracelet?',
        a: "The bracelet is available only as part of Crystal Code Premium. It's designed to complement the complete system, not as a standalone product.",
      },
      {
        q: 'Is Crystal Code Premium worth it?',
        a: "If you want a complete experience that integrates understanding your patterns into daily life, yes. The $40 difference adds a constant physical reminder that reinforces the process beyond the portal.",
      },
    ],
  },
];

function FAQItem({ q, a, isOpen, onToggle }) {
  return (
    <div className="border-b border-white/5">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between py-5 text-left"
      >
        <span className="text-white/90 font-sans font-medium pr-8">{q}</span>
        <motion.span
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
          className="text-gold flex-shrink-0"
        >
          <ChevronDown size={20} />
        </motion.span>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <p className="text-white/60 pb-5 leading-relaxed font-sans">{a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FAQ() {
  // Track open item per category: { catIndex: itemIndex }
  const [openMap, setOpenMap] = useState({});

  const toggle = (catIdx, itemIdx) => {
    setOpenMap(prev => {
      const current = prev[catIdx];
      return { ...prev, [catIdx]: current === itemIdx ? -1 : itemIdx };
    });
  };

  return (
    <main className="relative min-h-screen bg-[#0B0B0B] pt-24 pb-20">
      <StarField count={40} />
      <div className="relative z-10 max-w-3xl mx-auto px-6 py-16">

        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-16"
        >
          <p className="text-xs uppercase tracking-[0.3em] mb-4 font-sans font-medium" style={metalStyle}>Support</p>
          <h1 className="font-serif text-4xl md:text-5xl">Frequently Asked Questions</h1>
        </motion.div>

        <div className="space-y-12">
          {categories.map((cat, catIdx) => (
            <motion.div
              key={cat.title}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.1 }}
              variants={{ visible: { transition: { staggerChildren: 0.1 } } }}
            >
              <motion.h2 variants={fadeUp} className="font-serif text-xl md:text-2xl mb-4">
                {cat.title}
              </motion.h2>
              <motion.div variants={fadeUp} className="card-glass rounded-2xl px-8">
                {cat.items.map((item, itemIdx) => (
                  <FAQItem
                    key={itemIdx}
                    q={item.q}
                    a={item.a}
                    isOpen={openMap[catIdx] === itemIdx}
                    onToggle={() => toggle(catIdx, itemIdx)}
                  />
                ))}
              </motion.div>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center mt-16"
        >
          <p className="text-white/50 font-sans mb-4">Still have questions?</p>
          <Link to="/contact" className="btn-ghost">Contact Us</Link>
        </motion.div>
      </div>
    </main>
  );
}
